### ISSUE TITLE
Expose repo information on CI

### ISSUE THREAD

**Issue by JuanitoFatas** [snap-ci/docs.snap-ci.com#13]
Hello, I am trying to add SnapCI support for an open source tool called: [danger](https://danger.systems), code review tool that runs on CI, currently it supports Circle, Travis, Jenkins, Buildkite, Semaphore, TeamCity, Xcode Bots, Drone, Surf and Bitrise.

SnapCI support will be possible if there are information for:
- repo url - The url of the repository currently being built. (for example, `https://github.com/snap-ci/docs.snap-ci.com`).
- repo slug - The slug (in form: owner_name/repo_name) of the repository currently being built. (for example, `snap-ci/docs.snap-ci.com`).

Would you consider expose these environment variables? Thanks!
## 

https://docs.snap-ci.com/environment-variables/

**Comment by suziejprince** [comment]
Hey @JuanitoFatas. Thanks for getting in touch. We are considering this request. We will get back to you. Thanks!

**Comment by suziejprince** [comment]
We have added this to our backlog. We will update this if we make this change. Thanks!
